# - name: "Install Node.js 13"
#   shell: |
#     # Install Node.js LTS version as our base Node.js version
#     curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
#     sudo apt-get install -y nodejs

#     # Use n version manager to use Node.js v13.8.0
#     sudo npm install -g n
#     sudo n 13.8.0

# - name: "Install PM2 Globally"
#   npm:
#     name: pm2
#     global: yes



- name: "update and upgrade apt packages"
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: "Remove some dependences that are not required"
  become: true
  apt:
    autoremove: yes

- name: "Install Node.js and NPM"
  apt:
    name:
      - "nodejs"
      - "npm"
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: latest