---
- name: Create backend app directory
  file:
    path: $HOME/backend-app
    state: directory

- name: "Copy files to server"
  ansible.builtin.copy:
    src: "files/artifact.tar.gz"
    dest: "$HOME/artifact.tar.gz"
    follow: yes


- name: "Unarchive artifacts and install NPM packages"
  become: true
  shell: |
    tar -xvf artifact.tar.gz .
    rm artifact.tar.gz
    sudo npm install



- name: start app
  become: true
  shell: |
    sudo pm2 stop default
    sudo pm2 start "npm run start"

